### ISSUE TITLE
Standardize and enforce the order of outputs

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#2261]
#2206 fixes an issue that outputs used to be sorted by amount, but this is either not possible or not desirable with ringct. The fix there randomizes the order, which solves the issue with the standard wallet, but similar bugs could still exist in other wallets. 

For example, MyMonero (which does not use much of the reference code base) at one time failed to sort the outputs by amount, which leaked information not only about the payments, but the wallet being used.

A better approach would be to sort by something public in the output, such as the output key, and enforce this in consensus (such enforcement would be efficient since it only requires comparing the outputs sequentially). This would prevent poorly-written wallets from leaking information.

**Comment by moneromooo-monero** [comment]
Good idea. I wanted to sort extra as well, as I think it might leak whether a tx was made with cold signing, etc.

**Comment by iamsmooth** [comment]
While we are at it we can consider the order of the inputs as well. Same issue with poorly-written wallets doing something stupid, like putting the largest input first.

**Comment by stoffu** [comment]
How about lexicographically sorting 32-byte data of key images and destination pubkeys for inputs and outputs, respectively?

**Comment by moneromooo-monero** [comment]
I think anything that is unambiguous and which can be checked without keys is fine.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2440

**Comment by moneromooo-monero** [comment]
+resolved

**Comment by stoffu** [comment]
After #2440 and the subsequent revert of output sorting which was flawed, the original idea of output sorting proposed here is actually not implemented. So at least it seems inappropriate to me to mark this issue as "resolved" (since it's not solved).

A workable alternative I can think of is to sort the outputs according to the Pedersen Commitments. Do we still care to add it, or is this not really relevant?
