### ISSUE TITLE
DB corruption 

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#706]
We've had several reports of DB corruption, mostly on Windows I think, that occur when the system crashes.

Perhaps this is due to less safe/async DB modes? If so we should consider switching those off after initial sync, when performance is most critical, so that later crashes don't corrupt the DB.

**Comment by fluffypony** [comment]
I've had DB corruption on OS X during normal shutdown on testnet and mainnet, as discussed on IRC. It was mostly solved by popping blocks, perhaps we should have a rollback strategy if the database is in an inconsistent state? Like rollback 30 blocks or something, and try again.

**Comment by iamsmooth** [comment]
I think it is better to fix the DB so it doesn't corrupt. That's the purpose of a DB right?

**Comment by fluffypony** [comment]
True - I think the readtxn changes make it more robust, since everything is wrapped in a transaction and rolls back if it fails or is interrupted? That was my understanding anyway.

**Comment by iamsmooth** [comment]
Makes sense, maybe this is already fixed then.

**Comment by hyc** [comment]
wrapping readtxns doesn't affect robustness, readtxns don't make changes anyway. What's important is to properly wrap write ops in an appropriate writetxn. I get the impression that reorgs are not using a batch properly to enclose all of their deletes/etc. so interrupting a reorg can leave things inconsistent.

**Comment by iamsmooth** [comment]
It's not really clear a reorg needs to be a single transaction to operate properly. As long as it is implemented as a sequence of pop_blocks followed by add_blocks, any sequences of these (assuming they are individually atomic transactions) should leave the db consistent.

**Comment by hyc** [comment]
Yeah, I see. popping a block removes all of the block's transactions in a single DB writetxn anyway, so this shouldn't have been the cause of whatever problem I saw.

**Comment by hyc** [comment]
I reproduced a corruption on the current 0.9.2, got a SEGV while syncing and then the DB was corrupted on next restart. The block_* tables all have 165824 entries but the hf_versions table has only 165823, so hf_versions didn't get updated in the same DB txn as the block info.
[fail.txt](https://github.com/monero-project/bitmonero/files/180814/fail.txt)

Here's the loglevel 3 output right up to the crash:
[log.txt](https://github.com/monero-project/bitmonero/files/180815/log.txt)
It shows that the thread on P2P4 was starting a checkpoint check, while the thread on P2P3 was starting to add a new block. Unfortunately Blockchain::check_against_checkpoints() isn't taking the CRITICAL_REGION_LOCAL(m_blockchain_lock) so both threads wind up using the same write txn. Then one of them commits while the other thread is still using the txn, and SEGV happens. And the commit happened before add_block was done, so hf_versions didn't get updated in that txn.

**Comment by iamsmooth** [comment]
Are all the known sources of corruption fixed now?

Maybe we can close this issue and open another one specifically on the general issue of sync-vs-async?

**Comment by luigi1111** [comment]
@iamsmooth Yes let's do that (I assume that is still relevant).

**Comment by NanoAkron** [comment]
@hyc how should we proceed from here?

**Comment by hyc** [comment]
I agree with @iamsmooth we can close this one and start a new issue.

As for a general solution - that's still not clear. My previous suggestion was that we still default to "fast" during initial sync, and step down to "safe" after the node is synchronized. Unfortunately

1. We still can't reliably tell when the node is sync'd - a previous patch for that actually just caused more spurious sync'd messages.
2. It doesn't really help those Windows users whose PCs crashed during syncing. (Then again, I'm not sure we should be trying to work around users with broken hardware.)

**Comment by luigi1111** [comment]
#1463
